services: mysql

language: python

env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
  - DB=mysql

before_install:
	- mysql -e "create database IF NOT EXISTS gestorpsi;" -uroot

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt

before_script:
  - mv gestorpsi/settings.py.TRAVIS gestorpsi/settings.py
  - mysqladmin create gpsi -u travis
  - python manage.py syncdb --noinput
  - python manage.py migrate

  - workon gestorpsi

script:
  - python manage.py test