services: mysql

language: python

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt

before_script:
  - mv gestorpsi/settings.py.TRAVIS gestorpsi/settings.py
  - mysqladmin create gpsi -u travis
  - python manage.py syncdb --noinput
  - python manage.py migrate

  - workon gestorpsi

script:
  - python manage.py test
#  - flake8 gestorpsi

#after_script:
#    - coveralls

# notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/87309c799eae69dfdbbc
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false